## Preprocessing

In [123]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [124]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(columns=['EIN', 'NAME'])

# Display the updated DataFrame
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [125]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
unique_counts = application_df.nunique()

# Display the unique counts
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [126]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
# View the value counts for the 'APPLICATION_TYPE' column
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Display the value counts
application_type_counts

# Define a threshold for what is considered "other" (e.g., less than 10 occurrences)
threshold = 10

# Identify values to replace with "Other"
to_replace = application_type_counts[application_type_counts < threshold].index

# Replace identified values with "Other"
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(to_replace, 'Other')

# Verify the replacement
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
Other       11
Name: count, dtype: int64

In [127]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 500

# Get the value counts for 'APPLICATION_TYPE'
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Create a list of application types to replace
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [128]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE# Define a cutoff value for classification counts below which values will be replaced with "Other"
cutoff_value = 100  # Adjust as necessary

# Get the value counts for the 'CLASSIFICATION' column
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Create a list of classification types to replace, those with counts less than the cutoff value
classification_types_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace these classification types with "Other" in the dataframe
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(classification_types_to_replace, 'Other')

# Check the updated value counts to ensure the replacement was successful
updated_classification_counts = application_df['CLASSIFICATION'].value_counts()
updated_classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [129]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
# Get the value counts for 'CLASSIFICATION'
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Filter to show only classification types with counts greater than 1
classification_counts_greater_than_1 = classification_counts[classification_counts > 1]

# Display the filtered value counts
classification_counts_greater_than_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [130]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
cutoff_value = 2000  # You can adjust this value as necessary to fit your needs

# Step 2: Get the value counts for 'CLASSIFICATION'
classification_counts = application_df['CLASSIFICATION'].value_counts()

# Step 3: Create a list of classifications to be replaced (those with counts less than the cutoff value)
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
Other     6062
C1200     4837
Name: count, dtype: int64

In [131]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
# Convert categorical data to numeric using pd.get_dummies
# Specify the columns you want to convert. For this example, let's convert 'APPLICATION_TYPE' and 'CLASSIFICATION'.

# Convert categorical variables to dummy/indicator variables
application_df_dummies = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'CLASSIFICATION'])

# Display the first few rows of the resulting DataFrame to verify the transformation
application_df_dummies.head()

,AFFILIATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,...,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C2000,CLASSIFICATION_Other
0,Independent,ProductDev,Association,1,0,N,5000,1,False,True,...,False,False,False,False,False,False,True,False,False,False
1,Independent,Preservation,Co-operative,1,1-9999,N,108590,1,False,False,...,True,False,False,False,False,False,False,False,True,False
2,CompanySponsored,ProductDev,Association,1,0,N,5000,0,False,False,...,False,False,True,False,False,False,False,False,False,True
3,CompanySponsored,Preservation,Trust,1,10000-24999,N,6692,1,False,False,...,True,False,False,False,False,False,False,False,True,False
4,Independent,Heathcare,Trust,1,100000-499999,N,142590,1,False,False,...,True,False,False,False,False,False,True,False,False,False

In [132]:
# Replace values in 'APPLICATION_TYPE' and 'CLASSIFICATION' with 'Other'
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_types_to_replace = application_type_counts[application_type_counts < 500].index.tolist()
application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(application_types_to_replace, 'Other')

classification_counts = application_df['CLASSIFICATION'].value_counts()
classifications_to_replace = classification_counts[classification_counts < 2000].index.tolist()
application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(classifications_to_replace, 'Other')

# Convert categorical columns to numeric using one-hot encoding
application_df_dummies = pd.get_dummies(application_df, columns=['APPLICATION_TYPE', 'CLASSIFICATION', 'AFFILIATION', 'USE_CASE', 'ORGANIZATION', 'SPECIAL_CONSIDERATIONS'])

# Convert 'INCOME_AMT' to a numeric format, one option is to use one-hot encoding as well
application_df_dummies = pd.get_dummies(application_df_dummies, columns=['INCOME_AMT'])

In [133]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
# Define the target variable (y) and features (X)
y = application_df_dummies['IS_SUCCESSFUL']
X = application_df_dummies.drop(columns=['IS_SUCCESSFUL'])

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [136]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
print("Scaling complete!")

Scaling complete!

## Compile, Train and Evaluate the Model

In [137]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
input_dim = X_train_scaled.shape[1]
nn.add(tf.keras.layers.Dense(units=64, activation='relu', input_dim=input_dim))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=32, activation='relu'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │           2,688 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,801 (18.75 KB)

 Trainable params: 4,801 (18.75 KB)

 Non-trainable params: 0 (0.00 B)

In [139]:
# Compile the model
#  YOUR CODE GOES HERE
# Compile the model
nn.compile(
    optimizer='adam',  # Optimizer for updating model weights
    loss='binary_crossentropy',  # Loss function for binary classification
    metrics=['accuracy']  # Metrics to evaluate model performance
)

# Print the model summary to verify the compilation
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │           2,688 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,801 (18.75 KB)

 Trainable params: 4,801 (18.75 KB)

 Non-trainable params: 0 (0.00 B)

In [141]:
# Train the model
#  YOUR CODE GOES HERE
# Train the model
history = nn.fit(
    X_train_scaled,   # Training features
    y_train,          # Training labels
    epochs=20,        # Number of epochs to train
    batch_size=32,    # Number of samples per gradient update
    validation_data=(X_test_scaled, y_test),  # Validation data to monitor performance
    verbose=1         # Verbosity mode (0 = silent, 1 = progress bar, 2 = one line per epoch)
)

Epoch 1/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7270 - loss: 0.5534 - val_accuracy: 0.7290 - val_loss: 0.5635
Epoch 2/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7321 - loss: 0.5532 - val_accuracy: 0.7274 - val_loss: 0.5623
Epoch 3/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7273 - loss: 0.5578 - val_accuracy: 0.7192 - val_loss: 0.5670
Epoch 4/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7290 - loss: 0.5525 - val_accuracy: 0.7188 - val_loss: 0.5672
Epoch 5/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7329 - loss: 0.5507 - val_accuracy: 0.7213 - val_loss: 0.5646
Epoch 6/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7352 - loss: 0.5482 - val_accuracy: 0.7265 - val_loss: 0.5606
Epoch 7/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7301 - loss: 0.5515 - val_accuracy: 0.7224 - val_loss: 0.5635
Epoch 8/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7344 - loss: 0.5488 - val_accuracy: 0.7245 - val_loss: 0.5610
Epoch 9/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7289 - loss: 0.5541 - val_accuracy: 0.7262 - val_loss: 0.5618
Epoch 10/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7333 - loss: 0.5492 - val_accuracy: 0.7258 - val_loss: 0.5612
Epoch 11/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7354 - loss: 0.5446 - val_accuracy: 0.7201 - val_loss: 0.5629
Epoch 12/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7372 - loss: 0.5462 - val_accuracy: 0.7261 - val_loss: 0.5606
Epoch 13/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7329 - loss: 0.5469 - val_accuracy: 0.7259 - val_loss: 0.5631
Epoch 14/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.7329 - loss: 0.5482 - val_accuracy: 0.7252 - val_loss: 0.5633
Epoch 15/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7341 - loss: 0.5426 - val_accuracy: 0.7254 - val_loss: 0.5646
Epoch 16/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7400 - loss: 0.5423 - val_accuracy: 0.7248 - val_loss: 0.5642
Epoch 17/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7359 - loss: 0.5425 - val_accuracy: 0.7226 - val_loss: 0.5624
Epoch 18/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7351 - loss: 0.5440 - val_accuracy: 0.7251 - val_loss: 0.5612
Epoch 19/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7377 - loss: 0.5447 - val_accuracy: 0.7213 - val_loss: 0.5629
Epoch 20/20
858/858 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7346 - loss: 0.5457 - val_accuracy: 0.7248 - val_loss: 0.5612

In [142]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 1ms/step - accuracy: 0.7248 - loss: 0.5612
Loss: 0.5612238049507141, Accuracy: 0.724781334400177

In [143]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
# Export the model to an HDF5 file
nn.save('AlphabetSoupCharity.h5')

print("Model saved to 'AlphabetSoupCharity.h5'")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Model saved to 'AlphabetSoupCharity.h5'